version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_product
    env_file:
      - ./environments/db.env
    # command: bash -c "bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails db:seed && bin/webpack --verbose && bundle exec puma -C config/puma.rb"
    command: bash -c "WEBPACKER_PRECOMPILE=false bundle exec rails assets:precompile && RAILS_ENV=production bin/webpack && bundle exec puma -C config/puma.rb"
    volumes:
      - .:/smart_gift
      - public-data:/smart_gift/public
      - tmp-data:/smart_gift/tmp
      - log-data:/smart_gift/log
    depends_on:
      - db
    environment:
      RAILS_ENV: production
      DATABASE_NAME: sample_app_production
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
  db:
    image: mysql:5.7.32
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/smart_gift/public
      - tmp-data:/smart_gift/tmp
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
