version: '3'
services:
  web:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/smart_gift
      - public-data:/smart_gift/public
      - tmp-data:/smart_gift/tmp
      - log-data:/smart_gift/log
    depends_on:
      - db
  db:
    image: mysql:5.7.32
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/smart_gift/public
      - tmp-data:/smart_gift/tmp
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
