version: 2
services:
  app:
    image: 400639973590.dkr.ecr.ap-northeast-1.amazonaws.com/smart_gift_rails:latest
    mem_limit: 268435456
    # command: bash -c "bin/webpack && bundle exec puma -C config/puma.rb"
    # assets:clobber
    # command: bash -c "bundle exec rails assets:clean && bundle exec rails assets:precompile && bin/webpack"
    command: bash -c "bin/webpack && bundle exec puma -C config/puma.rb"
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: 4dbb0f4f6a8226a44ac588a9ed0e9e6f
      DATABASE_NAME: sample_app_production
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: password
      DATABASE_HOST: sample-app-db.cwdygbxeaznj.ap-northeast-1.rds.amazonaws.com
      TZ: Japan
      WEBPACKER_PRECOMPILE: 'false'
      NODE_OPTIONS: "--max_old_space_size=1536"
    working_dir: /smart_gift
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: sample-app-production/app
        awslogs-stream-prefix: sample-app-production
  nginx:
    image: 400639973590.dkr.ecr.ap-northeast-1.amazonaws.com/smart_gift_nginx:latest
    mem_limit: 268435456
    ports:
      - 80:80
    links:
      - app
    volumes_from:
      - app
    working_dir: /smart_gift
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-northeast-1
        awslogs-group: sample-app-production/nginx
        awslogs-stream-prefix: sample-app-production